// Data — artworks, exhibitions, worlds, studio notes.
// Imagery is procedurally drawn (gradients + subtle abstract layers) so the
// site feels like real photography of paintings without using stock photos.

const ARTWORKS = [
  {
    id: "w-1",
    title: "Morning, with the window open",
    medium: "Oil on linen",
    size_in: "48 × 36 in.",
    size_cm: "(122 × 91 cm)",
    year: 2025,
    series: "Rooms at dawn",
    status: "On view",
    edition: null,
    price: "Inquire",
    palette: ["#FFD4B8", "#FF9A75", "#C44A1F", "#2C1208"],
    grad: "linear-gradient(155deg, #FFE2C9 0%, #FF9A75 38%, #C44A1F 78%, #3B1610 100%)",
    note: "Painted over five mornings in late February. The window faces east; the room is a former pharmacy on the second floor.",
  },
  {
    id: "w-2",
    title: "A blue room, briefly",
    medium: "Graphite on paper",
    size_in: "14 × 11 in.",
    size_cm: "(36 × 28 cm)",
    year: 2024,
    series: "Drawings",
    status: "Sold",
    edition: null,
    price: "—",
    palette: ["#4A7FB8", "#C99AAF", "#FF9A75", "#1B2638"],
    grad: "linear-gradient(170deg, #6E96C4 0%, #C99AAF 50%, #F2B499 100%)",
    note: "A study from the same room. The blue is the wall before sunrise.",
  },
  {
    id: "w-3",
    title: "Hours, before noon",
    medium: "Oil on linen",
    size_in: "60 × 48 in.",
    size_cm: "(152 × 122 cm)",
    year: 2025,
    series: "Rooms at dawn",
    status: "On view",
    edition: null,
    price: "Inquire",
    palette: ["#FFF4DC", "#FFB347", "#E8801A", "#5A2A08"],
    grad: "linear-gradient(165deg, #FFF4DC 0%, #FFD188 45%, #E8801A 100%)",
    note: "The largest painting in the series. Painted standing up, in the middle of the room.",
  },
  {
    id: "w-4",
    title: "Late winter, north light",
    medium: "Oil on panel",
    size_in: "24 × 18 in.",
    size_cm: "(61 × 46 cm)",
    year: 2024,
    series: "Rooms at dawn",
    status: "On view",
    edition: null,
    price: "Inquire",
    palette: ["#2B2418", "#C99A3D", "#F4E4B8", "#0E0A06"],
    grad: "linear-gradient(165deg, #1F1A12 0%, #6E5A2E 50%, #F4E4B8 100%)",
    note: "A small painting, finished in a single afternoon.",
  },
  {
    id: "w-5",
    title: "Quiet hour",
    medium: "Charcoal on paper",
    size_in: "22 × 30 in.",
    size_cm: "(56 × 76 cm)",
    year: 2025,
    series: "Drawings",
    status: "Sold",
    edition: null,
    price: "—",
    palette: ["#ECE5DB", "#B8A893", "#80705F", "#2A2218"],
    grad: "linear-gradient(150deg, #ECE5DB 0%, #B8A893 60%, #5A4E40 100%)",
    note: "Charcoal lifted with bread. The kind of drawing I make on days I can't paint.",
  },
  {
    id: "w-6",
    title: "An open door, again",
    medium: "Oil on linen",
    size_in: "36 × 36 in.",
    size_cm: "(91 × 91 cm)",
    year: 2025,
    series: "Rooms at dawn",
    status: "On view",
    edition: null,
    price: "Inquire",
    palette: ["#5A1A0A", "#C0341A", "#FF7A3D", "#FFD4B8"],
    grad: "linear-gradient(140deg, #FFD4B8 0%, #FF7A3D 40%, #C0341A 78%, #2A0A04 100%)",
    note: "Square, almost a doorway itself.",
  },
  {
    id: "w-7",
    title: "Studio floor, October",
    medium: "Oil on linen",
    size_in: "30 × 40 in.",
    size_cm: "(76 × 102 cm)",
    year: 2023,
    series: "Interiors",
    status: "Sold",
    edition: null,
    price: "—",
    palette: ["#F0D8B8", "#B88860", "#6B4A2A", "#1A1208"],
    grad: "linear-gradient(170deg, #F0D8B8 0%, #B88860 55%, #2A1A0E 100%)",
    note: "Painted while sitting on the floor.",
  },
  {
    id: "w-8",
    title: "Two windows, faintly",
    medium: "Oil on linen",
    size_in: "40 × 60 in.",
    size_cm: "(102 × 152 cm)",
    year: 2024,
    series: "Interiors",
    status: "On view",
    edition: null,
    price: "Inquire",
    palette: ["#E8DFD0", "#A8B4C8", "#5A6B8A", "#1A2030"],
    grad: "linear-gradient(180deg, #E8DFD0 0%, #A8B4C8 50%, #1A2030 100%)",
    note: "A wider canvas, almost a horizon.",
  },
  {
    id: "w-9",
    title: "After rain, the room held still",
    medium: "Oil on panel",
    size_in: "18 × 24 in.",
    size_cm: "(46 × 61 cm)",
    year: 2025,
    series: "Rooms at dawn",
    status: "On view",
    edition: null,
    price: "Inquire",
    palette: ["#D8C8A8", "#A89878", "#584834", "#0E0A04"],
    grad: "linear-gradient(160deg, #D8C8A8 0%, #8A7858 60%, #100A04 100%)",
    note: "A panel; smooth ground; quieter brushwork.",
  },
];

// Editions — limited prints, app-icon-style tiles
const EDITIONS = [
  { id: "e-1", title: "Sunrise, study I",   ed: "Edition of 30", size: "12 × 16 in.", price: "$420",  grad: "linear-gradient(135deg, #FFD4B8, #FF7A3D 70%, #5A1A0A)" },
  { id: "e-2", title: "Window, plate II",    ed: "Edition of 25", size: "11 × 14 in.", price: "$380",  grad: "linear-gradient(150deg, #FFF4DC, #FFB347 60%, #E8801A)" },
  { id: "e-3", title: "Blue hour",          ed: "Edition of 40", size: "10 × 12 in.", price: "$320",  grad: "linear-gradient(165deg, #C2D2E8, #6E96C4 55%, #2A4A6B)" },
  { id: "e-4", title: "Mauve, with peach",  ed: "Edition of 30", size: "12 × 12 in.", price: "$420",  grad: "linear-gradient(140deg, #E8DDEC, #C99AAF 50%, #FF9A75)" },
  { id: "e-5", title: "Charcoal field",     ed: "Edition of 50", size: "9 × 12 in.",  price: "$260",  grad: "linear-gradient(170deg, #ECE5DB, #80705F 55%, #1A1410)" },
  { id: "e-6", title: "Golden plate",       ed: "Edition of 20", size: "14 × 11 in.", price: "$520",  grad: "linear-gradient(155deg, #F4E4B8, #C99A3D 55%, #2B2418)" },
];

// Exhibitions & events
const EXHIBITIONS = [
  { id: "x-1", year: 2026, season: "Spring", title: "Rooms at dawn — open studio",
    venue: "The studio, second floor", city: "Tarrytown, NY",
    dates: "April 18 — June 14, 2026",
    status: "Upcoming",
    blurb: "Nine paintings shown together for the first time. By appointment, Thursdays through Sundays. There will be no reception." },
  { id: "x-2", year: 2025, season: "Autumn", title: "Drawings, in conversation",
    venue: "Galería Pequeña", city: "Mexico City, MX",
    dates: "October 9 — November 23, 2025",
    status: "On view",
    blurb: "A two-person show with the painter Inés Vidal. Twelve drawings; twelve of hers." },
  { id: "x-3", year: 2025, season: "Summer", title: "Interiors, 2018 — 2024",
    venue: "Marta-Eve Project Space", city: "Berlin, DE",
    dates: "June 4 — August 30, 2025",
    status: "Past",
    blurb: "A small retrospective of interior paintings." },
  { id: "x-4", year: 2024, season: "Winter", title: "Late winter, north light",
    venue: "Bellweather Books", city: "Brooklyn, NY",
    dates: "January 19 — March 3, 2024",
    status: "Past",
    blurb: "Six paintings hung among the shelves. A bookshop, by design." },
  { id: "x-5", year: 2023, season: "Autumn", title: "The room is the painting",
    venue: "Kammer 12", city: "Vienna, AT",
    dates: "September 14 — December 10, 2023",
    status: "Past",
    blurb: "A solo show; a long winter; a quiet opening." },
];

// Worlds — bodies of work, themed series
const WORLDS = [
  { id: "wl-1", title: "Rooms at dawn", count: 9, years: "2024 — present",
    grad: "linear-gradient(155deg, #FFE2C9 0%, #FF9A75 45%, #C44A1F 100%)",
    blurb: "Paintings of the studio in the hour before the day begins. The light is doing most of the work." },
  { id: "wl-2", title: "Interiors", count: 14, years: "2018 — 2024",
    grad: "linear-gradient(165deg, #E8DFD0 0%, #A8B4C8 50%, #1A2030 100%)",
    blurb: "Rooms I have lived in, rented, borrowed. A loose decade of looking at walls." },
  { id: "wl-3", title: "Drawings", count: 42, years: "Ongoing",
    grad: "linear-gradient(150deg, #ECE5DB 0%, #B8A893 55%, #1A1410 100%)",
    blurb: "Graphite and charcoal — the daily practice. Small, fast, often given away." },
  { id: "wl-4", title: "Editions & plates", count: 6, years: "2021 — present",
    grad: "linear-gradient(140deg, #F4E4B8 0%, #C99A3D 50%, #2B2418 100%)",
    blurb: "Hand-pulled prints from copper and zinc plates. Numbered and signed, never re-issued." },
];

// Studio notes — short journal entries
const NOTES = [
  { id: "n-1", date: "March 14, 2026",  title: "A week of false starts",
    body: "The light has been wrong. I rehung two paintings and started a third." },
  { id: "n-2", date: "February 27, 2026", title: "On scraping back",
    body: "I scraped back the floor of \u201CHours, before noon\u201D and started it again. The first version was a polite painting. Polite paintings don't last in this room." },
  { id: "n-3", date: "January 12, 2026", title: "The studio is colder than I thought",
    body: "I am painting in two sweaters. The cold slows the work down, which is not a bad thing." },
];

window.ARTWORKS = ARTWORKS;
window.EDITIONS = EDITIONS;
window.EXHIBITIONS = EXHIBITIONS;
window.WORLDS = WORLDS;
window.NOTES = NOTES;
